Geldawyn15/PokeBnb

Gemfile, Gemfile.lock, app/models/battle.rb, app/models/pokemon.rb, app/models/review.rb, app/models/transfer.rb, app/models/user.rb, db/migrate/20190520134608_devise_create_users.rb, db/migrate/20190520135905_create_pokemons.rb, db/migrate/20190520140210_create_transfers.rb, db/migrate/20190520140545_create_reviews.rb, db/migrate/20190520142547_change_battles_to_transfers.rb, db/schema.rb, db/seeds.rb
Validations, relations and seed.rb are all working as intended
=> Validations

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, config/routes.rb
Please check if user creation / login / edit works
http://localhost:3000/users/sign_up
http://localhost:3000/users/sign_in
http://localhost:3000/users/edit
=> user sign_in sign_up edit done with devise - no front end

app/controllers/pages_controller.rb, app/controllers/pokemons_controller.rb, app/views/pokemons/search.html.erb
Authentication issues for home and search fixed
=> authentication issues resolved

app/views/pokemons/search.html.erb, app/views/shared/_poke-card.html.erb
=> Search front

app/assets/stylesheets/components/_simpleform.scss, app/views/pokemons/search.html.erb, app/views/shared/_searchbar.html.erb, db/seeds.rb
=> Better seed

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_poke_card.scss
Change or add color for all the pokemon cards by pokemon type
=> pokemon card by pokemon type

app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb
=> a bit of padding

app/assets/stylesheets/pages/_home.scss, app/views/pokemons/home.html.erb
Ajout du responsive sur la page home au niveau des cards.
=> Responsive home

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_home-form.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_searchbar.scss, app/models/transfer.rb, app/views/pokemons/edit.html.erb, app/views/pokemons/home.html.erb, app/views/pokemons/new.html.erb, app/views/pokemons/show.html.erb, app/views/reviews/new.html.erb, app/views/shared/_searchbar.html.erb
responsive navbar done
rewriting in DRY MODE the _buttons.css and adding a class "btn" everywhere there is a button
=> Responsive searchbar

Gemfile, Gemfile.lock
=> ffi updated

app/models/transfer.rb
removed line that broke heroku
=> fix heroku

app/controllers/pokemons_controller.rb, db/seeds.rb
nidorans of all genders welcome
=> please work

app/views/pokemons/home.html.erb
Changement de l'affichage des cards sur Home qui affichait toutes les cards.
=> correction home cards

app/assets/stylesheets/pages/_home.scss, app/views/pokemons/home.html.erb
Normalement la home page est 100% fonctionnelle
=> Home cards clickable

config/routes.rb
transfers/new  added to routes
=> routes restored

app/javascript/packs/application.js
removed a line that broke heroku deployment
=> heroku error

db/seeds.rb
DRY for seed and anna's account created
=> anna's account created

app/views/users/show.html.erb
Ajout du If/else sur le render des pokecards et transfer cards
=> if/else user_page

app/assets/stylesheets/pages/_transfer_page.scss, app/views/shared/_transfer_page.html.erb
=> Transfer edit

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_review.scss, app/assets/stylesheets/components/_separator.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_pokemon_show.scss, app/controllers/pokemons_controller.rb, app/controllers/transfers_controller.rb, app/views/layouts/application.html.erb, app/views/pokemons/show.html.erb, app/views/shared/_separator.html.erb, config/routes.rb
=> Pokemon show enhenced

app/views/shared/_show.html.erb, config/routes.rb
=> Transfer cards good

config/routes.rb
=> correction du trasnfer
